spring.application.name=mcp_client

spring.ai.ollama.base-url=http://127.0.0.1:11434
spring.ai.ollama.chat.options.model=granite4:3b
spring.ai.ollama.chat.options.temperature=0.1

spring.ai.mcp.client.toolcallback.enabled=true
spring.ai.mcp.client.sse.connections.mcp_server.url=http://localhost:8081
